import { Agent, Task, ApprovalItem, DailyStats, Notification } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-001',
    name: 'Finance Agent',
    type: 'Finance Automation',
    status: 'running',
    tasksCompleted: 1847,
    tasksToday: 43,
    errorRate: 0.8,
    uptime: '99.2%',
    lastActivity: '2 detik lalu',
    currentTask: 'Membaca invoice PT. Sumber Makmur #INV-2024-0891',
    icon: '🧾',
  },
  {
    id: 'agent-002',
    name: 'HR & Attendance Agent',
    type: 'HR & Attendance',
    status: 'running',
    tasksCompleted: 923,
    tasksToday: 28,
    errorRate: 0.3,
    uptime: '99.8%',
    lastActivity: '15 detik lalu',
    currentTask: 'Rekonsiliasi data kehadiran karyawan Shift 1',
    icon: '🔄',
  },
  {
    id: 'agent-003',
    name: 'B2B Buyer Scraper',
    type: 'B2B Leads Prospector',
    status: 'running',
    tasksCompleted: 3204,
    tasksToday: 67,
    errorRate: 1.2,
    uptime: '98.9%',
    lastActivity: '3 menit lalu',
    currentTask: 'Mencari kontak purchasing logistik di Serang',
    icon: '📧',
  },
  {
    id: 'agent-004',
    name: 'Attendance Automator',
    type: 'HR & Attendance',
    status: 'idle',
    tasksCompleted: 512,
    tasksToday: 0,
    errorRate: 0.5,
    uptime: '100%',
    lastActivity: '1 jam lalu',
    currentTask: undefined,
    icon: '📋',
  },
  {
    id: 'agent-005',
    name: 'Report Generator',
    type: 'Finance Automation',
    status: 'running',
    tasksCompleted: 289,
    tasksToday: 12,
    errorRate: 0.0,
    uptime: '100%',
    lastActivity: '5 menit lalu',
    currentTask: 'Menyusun laporan keuangan harian',
    icon: '📊',
  },
  {
    id: 'agent-006',
    name: 'Audit Compliance Bot',
    type: 'Finance Automation',
    status: 'error',
    tasksCompleted: 178,
    tasksToday: 3,
    errorRate: 8.4,
    uptime: '91.2%',
    lastActivity: '20 menit lalu',
    currentTask: undefined,
    icon: '🔍',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'OCR Invoice PT. Sumber Makmur',
    type: 'invoice_ocr',
    status: 'processing',
    agentId: 'agent-001',
    agentName: 'Finance Agent',
    priority: 'high',
    startedAt: '14:05:32',
    source: 'Email (finance@indahkiat.com)',
    destination: 'Google Sheets - Rekap Invoice Juni',
    confidence: 94,
    documentName: 'INV-SM-2024-0891.pdf',
  },
  {
    id: 'task-101',
    title: 'Ekstraksi Struk Bensin Pertamina',
    type: 'invoice_ocr',
    status: 'completed',
    agentId: 'agent-001',
    agentName: 'Finance Agent',
    priority: 'medium',
    startedAt: '13:12:00',
    completedAt: '13:12:45',
    duration: 45,
    source: 'Telegram Bot upload',
    destination: 'Database Pengeluaran - Kas Kecil',
    confidence: 98,
    documentName: 'receipt-pertamina-88.jpg',
  },
  {
    id: 'task-102',
    title: 'Analisis Invoice Pembelian ATK',
    type: 'invoice_ocr',
    status: 'completed',
    agentId: 'agent-001',
    agentName: 'Finance Agent',
    priority: 'low',
    startedAt: '11:45:00',
    completedAt: '11:46:10',
    duration: 70,
    source: 'Document Scanner Web',
    destination: 'Database Pengeluaran - Inventaris',
    confidence: 97,
    documentName: 'INV-OFFICE-99.pdf',
  },
  {
    id: 'task-003',
    title: 'Rekap Stok Gudang Juni',
    type: 'reconciliation',
    status: 'waiting_approval',
    agentId: 'agent-002',
    agentName: 'HR & Attendance Agent',
    priority: 'critical',
    startedAt: '13:30:00',
    source: 'Google Sheets - Stok Masuk/Keluar',
    destination: 'Laporan Stok Bulanan',
    confidence: 71,
    documentName: 'stok-gudang-juni.xlsx',
  },
  {
    id: 'task-007',
    title: 'Rekonsiliasi Bank Statement',
    type: 'reconciliation',
    status: 'pending',
    agentId: 'agent-002',
    agentName: 'HR & Attendance Agent',
    priority: 'high',
    startedAt: '14:10:00',
    source: 'Bank BCA - Mutasi Harian',
    destination: 'Accurate - Jurnal Penerimaan',
    documentName: 'mutasi-bca-29jun2024.csv',
  },
  {
    id: 'task-201',
    title: 'Verifikasi Absensi Shift Malam',
    type: 'data_entry',
    status: 'completed',
    agentId: 'agent-002',
    agentName: 'HR & Attendance Agent',
    priority: 'medium',
    startedAt: '09:15:00',
    completedAt: '09:16:30',
    duration: 90,
    source: 'Fingerprint SDK',
    destination: 'Database HR - Shift Malam',
    confidence: 99,
  },
  {
    id: 'task-002',
    title: 'Input PO Buyer Tangerang',
    type: 'data_entry',
    status: 'completed',
    agentId: 'agent-003',
    agentName: 'B2B Buyer Scraper',
    priority: 'medium',
    startedAt: '13:58:10',
    completedAt: '14:01:44',
    duration: 214,
    source: 'Email (buyer@tokobesar.com)',
    destination: 'Odoo ERP - Purchase Orders',
    confidence: 99,
    documentName: 'PO-TB-20240629.pdf',
  },
  {
    id: 'task-301',
    title: 'Scraping Kontak Purchasing Serang',
    type: 'data_entry',
    status: 'completed',
    agentId: 'agent-003',
    agentName: 'B2B Buyer Scraper',
    priority: 'high',
    startedAt: '12:00:00',
    completedAt: '12:03:15',
    duration: 195,
    source: 'LinkedIn Sales Navigator API',
    destination: 'Database Leads - Logistik Serang',
    confidence: 95,
  },
  {
    id: 'task-302',
    title: 'Scraping Buyer Tekstil Bandung',
    type: 'data_entry',
    status: 'completed',
    agentId: 'agent-003',
    agentName: 'B2B Buyer Scraper',
    priority: 'medium',
    startedAt: '10:30:00',
    completedAt: '10:35:40',
    duration: 340,
    source: 'Google Maps & Web Scraper',
    destination: 'Database Leads - Industri Bandung',
    confidence: 96,
  },
  {
    id: 'task-006',
    title: 'Entry Absensi Karyawan',
    type: 'data_entry',
    status: 'completed',
    agentId: 'agent-004',
    agentName: 'Attendance Automator',
    priority: 'low',
    startedAt: '08:00:00',
    completedAt: '08:04:21',
    duration: 261,
    source: 'Mesin Absensi (FTP)',
    destination: 'Sistem HR - Attendance Module',
    confidence: 100,
  },
  {
    id: 'task-401',
    title: 'Sinkronisasi Log Mesin C3 Serang',
    type: 'data_entry',
    status: 'completed',
    agentId: 'agent-004',
    agentName: 'Attendance Automator',
    priority: 'medium',
    startedAt: '07:30:00',
    completedAt: '07:31:45',
    duration: 105,
    source: 'Mesin Absensi C3 (IP: 192.168.10.5)',
    destination: 'Sistem HR - DB Kehadiran',
    confidence: 100,
  },
  {
    id: 'task-004',
    title: 'Generate Laporan Keuangan Harian',
    type: 'report_gen',
    status: 'processing',
    agentId: 'agent-005',
    agentName: 'Report Generator',
    priority: 'high',
    startedAt: '14:00:00',
    source: 'Database Akuntansi',
    destination: 'Email Report → Direktur',
    confidence: 98,
  },
  {
    id: 'task-501',
    title: 'Penyusunan Neraca Laba Rugi Q2',
    type: 'report_gen',
    status: 'completed',
    agentId: 'agent-005',
    agentName: 'Report Generator',
    priority: 'critical',
    startedAt: '09:00:00',
    completedAt: '09:12:30',
    duration: 750,
    source: 'Buku Besar Akuntansi (PostgreSQL)',
    destination: 'Dropbox - Financial Reports',
    confidence: 100,
  },
  {
    id: 'task-005',
    title: 'Parse Invoice Vendor Listrik',
    type: 'invoice_ocr',
    status: 'failed',
    agentId: 'agent-006',
    agentName: 'Audit Compliance Bot',
    priority: 'medium',
    startedAt: '13:20:00',
    completedAt: '13:21:05',
    duration: 65,
    source: 'Email (pln@vendorlistrik.co.id)',
    destination: 'Google Sheets - Tagihan Operasional',
    confidence: 32,
    documentName: 'tagihan-listrik-jun24.pdf',
    errorMessage: 'Format dokumen tidak dikenali. PDF terenkripsi.',
  },
  {
    id: 'task-601',
    title: 'Audit Kas Kecil Serang Plant 2',
    type: 'invoice_ocr',
    status: 'completed',
    agentId: 'agent-006',
    agentName: 'Audit Compliance Bot',
    priority: 'high',
    startedAt: '10:00:00',
    completedAt: '10:01:20',
    duration: 80,
    source: 'Database Kas Kecil',
    destination: 'Sistem Laporan Audit Internal',
    confidence: 99,
  },
];

export const mockApprovalItems: ApprovalItem[] = [
  {
    id: 'appr-001',
    taskId: 'task-003',
    documentName: 'stok-gudang-juni.xlsx',
    documentType: 'Rekap Stok Gudang',
    agentName: 'HR & Attendance Agent',
    submittedAt: '13:45:00',
    confidence: 71,
    priority: 'critical',
    reason: 'Confidence score rendah (71%) — terdapat perbedaan jumlah stok antara sistem dan fisik',
    extractedData: {
      'Periode': 'Juni 2024',
      'Total SKU': '1.247',
      'Stok Fisik (sistem)': 'Rp 4.821.500.000',
      'Stok Fisik (hitung ulang)': 'Rp 4.793.200.000',
      'Selisih': 'Rp 28.300.000',
      'Item Tidak Cocok': '14 item',
      'Gudang': 'Serang Plant 2',
    },
    rawText: 'Rekap Stok Gudang Juni 2024\nSerang Plant 2\n\nTotal SKU: 1.247\nNilai sistem: Rp 4.821.500.000\nNilai fisik: Rp 4.793.200.000\nSelisih: Rp 28.300.000\n\nItem dengan selisih:\n1. Kertas A4 80gr (SKU-0012): sistem=500 rim, fisik=487 rim...',
  },
  {
    id: 'appr-002',
    taskId: 'task-008',
    documentName: 'PO-OVERSEAS-004521.pdf',
    documentType: 'Purchase Order',
    agentName: 'B2B Buyer Scraper',
    submittedAt: '13:55:00',
    confidence: 68,
    priority: 'high',
    reason: 'Dokumen berbahasa campuran (Inggris-Mandarin), validasi manual diperlukan',
    extractedData: {
      'Vendor': 'Zhejiang Paper Co., Ltd.',
      'No. PO': 'PO-OS-2024-004521',
      'Tanggal': '28 Juni 2024',
      'Total Nilai': 'USD 127.500',
      'Mata Uang': 'USD',
      'Incoterm': 'CIF Tanjung Priok',
      'Payment Terms': 'T/T 30 days',
    },
    rawText: 'PURCHASE ORDER\nZhejiang Paper Co., Ltd.\nNo: PO-OS-2024-004521\nDate: June 28, 2024\n\n采购订单明细...',
  },
];

export const mockDailyStats: DailyStats[] = [
  { date: '23 Jun', tasksCompleted: 142, tasksFailed: 3, hoursSaved: 18.4, documentsProcessed: 89 },
  { date: '24 Jun', tasksCompleted: 168, tasksFailed: 5, hoursSaved: 21.2, documentsProcessed: 104 },
  { date: '25 Jun', tasksCompleted: 155, tasksFailed: 2, hoursSaved: 19.8, documentsProcessed: 97 },
  { date: '26 Jun', tasksCompleted: 201, tasksFailed: 7, hoursSaved: 24.6, documentsProcessed: 118 },
  { date: '27 Jun', tasksCompleted: 187, tasksFailed: 4, hoursSaved: 23.1, documentsProcessed: 112 },
  { date: '28 Jun', tasksCompleted: 223, tasksFailed: 3, hoursSaved: 27.3, documentsProcessed: 134 },
  { date: '29 Jun', tasksCompleted: 153, tasksFailed: 8, hoursSaved: 18.9, documentsProcessed: 91 },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'warning',
    title: 'Butuh Review',
    message: 'Finance Intern AI mendeteksi selisih rekonsiliasi PT. Sumber Makmur. Confidence 71%.',
    timestamp: '13:45',
    read: false,
  },
  {
    id: 'notif-002',
    type: 'error',
    title: 'Audit Compliance Bot Alert',
    message: 'Gagal memproses tagihan listrik. File PDF terenkripsi, butuh bypass manual.',
    timestamp: '13:21',
    read: false,
  },
  {
    id: 'notif-003',
    type: 'success',
    title: 'Otomasi Purchasing Sukses',
    message: '12 Purchase Order (PO) berhasil digenerate otonom oleh Purchasing Specialist AI.',
    timestamp: '12:30',
    read: true,
  },
  {
    id: 'notif-004',
    type: 'info',
    title: 'SOP Sync Sukses',
    message: 'Regulasi onboarding kontraktor lapangan berhasil disinkronkan oleh HR Manager AI.',
    timestamp: '08:05',
    read: true,
  },
];
